[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/chat/tts"
  to = "/.netlify/functions/chat-tts"
  status = 200

[[redirects]]
  from = "/api/chat/reset"
  to = "/.netlify/functions/chat-reset"
  status = 200

[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200
